name: Build

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            runtime: linux-x64
            name: linux
          - os: windows-latest
            runtime: win-x64
            name: windows
          - os: macos-14
            runtime: osx-arm64
            name: macos-arm64
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    - name: Build extension
      run: dotnet publish -c Release -r ${{ matrix.runtime }} --self-contained
      working-directory: ./src
    
    - name: Make the mac build universal with x64 support
      if: matrix.name == 'macos-arm64'
      run: |
        dotnet publish -c Release -r osx-x64 --self-contained
        arm=$(ls GMInk/bin/Release/net*/osx-arm64/publish/GMInk.dylib)
        x64=$(ls GMInk/bin/Release/net*/osx-x64/publish/GMInk.dylib)
        lipo -create -output GMInk.universal.dylib "$arm" "$x64"
        mv GMInk.universal.dylib "$arm"
        lipo -info "$arm"
        rm -rf GMInk/bin/Release/net*/osx-*/publish/*.dSYM
      working-directory: ./src

    - name: Sign the macos version
      if: matrix.name == 'macos-arm64'
      run: codesign --force -s - src/GMInk/bin/Release/net*/${{ matrix.runtime }}/publish/GMInk.dylib

    - name: Prepare artifacts
      run: |
        mkdir artifacts
        cp src/GMInk/bin/Release/net*/${{ matrix.runtime }}/publish/* artifacts/
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: tmp-${{ matrix.name }}
        path: artifacts/
  
  package:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download Linux artifacts
      uses: actions/download-artifact@v4
      with:
        name: tmp-linux
        path: linux
        
    - name: Download Windows artifacts
      uses: actions/download-artifact@v4
      with:
        name: tmp-windows
        path: windows
    
    - name: Download macos artifacts
      uses: actions/download-artifact@v4
      with:
        name: tmp-macos-arm64
        path: macos
    
    - name: Prepare artifacts
      run: |
        mkdir artifacts
        mv linux/* artifacts/
        mv windows/* artifacts/
        mv macos/* artifacts/
        mv src/gm-files/* artifacts/
        
    - name: Upload combined artifacts
      uses: actions/upload-artifact@v4
      with:
        name: GMInk
        path: artifacts/

